site_name: MoDeS3 SmartCity
pages:
- 'Introduction': 'index.md'
- 'Blog':
    - 'Gamma over DDS':
        - 'DDS Implementation': 'blog/opensplice_dds.md'
        - 'List of technologies used': 'blog/codegen/Technologies.md'
        - 'Code Generation': 'blog/codegen/CodeGen.md'
    - 'Dashboard': 
        - 'Introduction': 'blog/dashboard/monitoring_solution.md'
        - 'Frontend': 'blog/dashboard/frontend.md'
    - 'IoT':
	    - 'IIot in smart cities': 'blog/iot/IIoT_Architecture.md'