site_name: MoDeS3 SmartCity
pages:
- 'Introduction': 'index.md'
- 'IoT Challenge Summary': 'summary.md'
- 'Blog':
    - 'Gamma over DDS':
        - 'Overview' : 'blog/overview_gamma_dds.md'
        - 'DDS Implementation': 'blog/opensplice_dds.md'
        - 'List of technologies used': 'blog/codegen/Technologies.md'
        - 'Code Generation': 'blog/codegen/CodeGen.md'
        - 'Demo': 'blog/codegen/demo-1.md'
    - 'Dashboard': 
        - 'Introduction': 'blog/dashboard/monitoring_solution.md'
        - 'Monitoring': 'blog/dashboard/monitoring.md'
        - 'Frontend': 'blog/dashboard/frontend.md'
        - 'Remote Terminal': 'blog/dashboard/SSH.md'
        - 'Deployment': 'blog/dashboard/deploy.md'
    - 'IoT':
        - 'Data Analysis': 'blog/iot/data_analysis.md'
        - 'Scheduler': 'blog/iot/scheduler.md'
        - 'IIot in smart cities': 'blog/iot/IIoT_Architecture.md'
- 'Technical Documentation':
    - 'Kura':
        - 'Installation Guide': 'technical_documentation/kura/kura_install guide.md'
    - 'DDS':
        - 'Java library for OpenSplice DDS': 'technical_documentation/dds/dds_java_lib.md'
